import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SessionProvider } from "next-auth/react";

const workSans = localFont({
  src : [
    {
      path : './fonts/WorkSans-Black.ttf',
      weight : '900',
      style : 'normal' 
    },
    {
      path : './fonts/WorkSans-ExtraBold.ttf',
      weight : '800',
      style : 'normal'
    },
    {
      path : './fonts/WorkSans-Bold.ttf',
      weight : '700',
      style : 'normal'
    },
    {
      path : './fonts/WorkSans-SemiBold.ttf',
      weight : '600',
      style : 'normal'
    },
    {
      path : './fonts/WorkSans-Medium.ttf',
      weight : '500',
      style : 'normal'
    },

  ],
  variable : '--font-work-sans'
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
} : Readonly<{
  children : React.ReactNode ;
}>) {
  return (
    <html lang="en">
      <body
        className={workSans.variable}
      >
        <SessionProvider>
            {children}
        </SessionProvider>
        
      </body>
    </html>
  );
}